/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
// This code is auto-generated by Plasmic; please do not edit!
// Plasmic Project: gY2snNpZVMz843KPnxWK1X
import { createUseGlobalVariants } from "@plasmicapp/react-web";
import { useScreenVariants as useScreenVariantspsmwmIUfnn6I } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: psmwmIUfnn6I/globalVariant

export const _useGlobalVariants = createUseGlobalVariants({
  screen: useScreenVariantspsmwmIUfnn6I
});
